[build]
  command = "npm install --prefix client && npm run build --prefix client"
  publish = "client/build"

[functions]
  directory = "netlify/functions"

[dev]
  command     = "npm start --prefix client"
  targetPort  = 3000
  port        = 8888
  autoLaunch  = false

[dev.environment]
  BROWSER = "none"
